apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: git-watchdog
test:
  - image: git-watchdog
    custom:
      - command: make test.unit
        timeoutSeconds: 60    
        dependencies:
          paths:
          -  "**/*_test.go"
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: git-watchdog
    docker:
      dockerfile: Dockerfile    
deploy:
  helm:
    releases:
    - name: local-helm
      chartPath: k8s
      artifactOverrides:
        image: git-watchdog
      imageStrategy:
        helm: {}
