apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-watchdog.fullname" . }}
  labels:
    {{- include "git-watchdog.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
data:  
  DB_NAME: "code-challenge"
  DB_USER: "dev"
  DB_ADDRESS: "mysql:3306"
  LOG_MODE: "production"
  LOG_LEVEL: "INFO"
  GIN_MODE: "release"
  AMQP_SERVER_URL: "amqp://guest:guest@rabbitmq:5672/"
