apiVersion: v1
kind: Secret
metadata:
  name: {{ include "git-watchdog.fullname" . }}
  labels:
    {{- include "git-watchdog.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation    
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  DB_PASSWORD: ZGV2